domains:
- domain: teerkaman.com.pk
  type: PRIMARY
  zone: teerkaman.com.pk
name: teerkaman
region: blr
static_sites:
- environment_slug: html
  git:
    branch: main
    repo_clone_url: https://github.com/abaidullahawan/sample-html.git
  name: teerkaman
  routes:
  - path: /teerkaman
